**Calcular indicadores geoespaciales de Clima**

# Setup

In [1]:
# define root path of project 
from pathlib import Path
import sys

ROOT = Path("..").resolve()
sys.path.append(str(ROOT))

# load general setup
from utils.setup_general import *

# load GIS setup
from utils.setup_gis_python import *

Setup general cargado
Setup GIS cargado

# Parámetros

# Definir archivo de salida
El archivo de salida se estructura para conservar la misma estructura entre todas las bases de datos

In [2]:
ORDEN_DF

['codigo_dane_municipio',
 'anno',
 'nombre_variable',
 'variable_sujeto',
 'variable_medicion',
 'variable_detalle',
 'variable_descripcion',
 'valor',
 'clasificacion_econometria']

In [3]:
# Definir DF con la estructura acordada para el proyecto
# La variable global ORDEN_DF ya tiene la lista de todas las columnas ordenadas
# Inicializar el DF vacío
dfOutput_indicadoresGeoespacialesClima = pd.DataFrame(
    columns=[ORDEN_DF]
)

# Poligonos de municipios

In [4]:
# rutas de poligonos
ruta_municipios = DATA/"raw/baa_DANE_poligonosMpiosDptos/ADMINISTRATIVO/MGN_ADM_MPIO_GRAFICO.shp"
ruta_departamentos = DATA/"raw/baa_DANE_poligonosMpiosDptos/ADMINISTRATIVO/MGN_ADM_DPTO_POLITICO.shp"

# cargar geo-data-frames
gdf_municipios = gpd.read_file(ruta_municipios)
gdf_departamentos = gpd.read_file(ruta_departamentos)


# nombre de la columna del codigo del municipio en gdf_municipios
col_id  = 'mpio_cdpmp'

# Validaciones
if gdf_municipios.crs is None:
    raise ValueError("El GeoDataFrame de municipios no tiene CRS definido.")

if gdf_municipios[col_id].isna().any() or gdf_municipios[col_id].duplicated().any():
    raise ValueError("Debe haber un código único y no vacío por municipio")

# Entender datos Raster

In [6]:
ruta_precipitacion = DATA/"raw/aca_CHIRPS_precipitacion/chirps-v3.0.1981.01.tif"


# Explorar los objetos de raster
with rasterio.open(ruta_precipitacion) as src:
    print("Número de bandas:", src.count)
    print("Filas:", src.height)
    print("Columnas:", src.width)
    print("Tipo de dato por banda:", src.dtypes)

    print("Sistema de coordenadas:", src.crs)
    print("Tamaño del píxel:", src.res)
    print("Límites:", src.bounds)
    print("Transformación:", src.transform)

    print("Valor sin información:", src.nodata)
    print("Descripción de bandas:", src.descriptions)
    
    # Extraer una banda
    banda = src.read(1, masked=True) # Las bandas de Rasterio empiezan en 1

# Explorar la banda
print(MSC_SEPARADOR, "Banda:")
print("Shape:", banda.shape)  # (filas, columnas)
print("Primer entrada:", banda[0, 0])  # Valor de la primera fila y primera columna

Número de bandas: 1
Filas: 1900
Columnas: 1720
Tipo de dato por banda: ('float32',)
Sistema de coordenadas: EPSG:4326
Tamaño del píxel: (0.05000000074505806, 0.05000000074505806)
Límites: BoundingBox(left=-120.0, bottom=-60.00000141561031, right=-33.99999871850014, top=35.0)
Transformación: | 0.05, 0.00,-120.00|
| 0.00,-0.05, 35.00|
| 0.00, 0.00, 1.00|
Valor sin información: None
Descripción de bandas: (None,)

-------------------------------- Banda:
Shape: (1900, 1720)
Primer entrada: 76.876816

# Ejemplo para un solo año

In [7]:

# Repetir para cada año

# ruta del archivo
ruta_precipitacion = DATA/"raw/aca_CHIRPS_precipitacion/chirps-v3.0.1981.01.tif"


with rasterio.open(ruta_precipitacion) as src:
    
    # Revisar que el raster tengo infor geografica
    if src.crs is None or not src.crs.is_geographic: 
        raise ValueError("Este ejemplo requiere un ráster en coordenadas geográficas")
    
    # Transformar los polígonos al CRS del ráster
    municipios_raster = gdf_municipios[[col_id, "geometry"]].to_crs(src.crs)
    
    # Media ponderada por el área cubierta de cada píxel
    resultados = exact_extract(
        src,
        municipios_raster,
        ["precipitacion_media=mean(coverage_weight=area_spherical_m2)"],
        include_cols=[col_id],
        output="pandas",
    )

# Mostrar resultado
display(resultados.head())

  mpio_cdpmp  precipitacion_media
0      05001                22.61
1      05002                41.25
2      05004                53.21
3      05021                52.37
4      05030                33.33

# CHIRPS - Precipitación

In [8]:
# Carpeta de los archivos
ruta_carpeta = DATA / "raw/aca_CHIRPS_precipitacion"

# DF con los periodos en los que tengo informacion
periodos = pd.date_range(
    start="2000-01-01",
    end="2026-08-01",
    freq="MS",
)

# Comprobar que estén todos los archivos antes de procesarlos ----------------

# Crear los nombres de los archivos
rutas = [ruta_carpeta / f"chirps-v3.0.{fecha.year}.{fecha.month:02d}.tif" for fecha in periodos]

# Revisar faltantes
faltantes = [ruta.name for ruta in rutas if not ruta.exists()]

# Reportar faltantes
if faltantes:
    raise FileNotFoundError(
        f"Faltan {len(faltantes)} archivos:\n" + "\n".join(faltantes)
    )
    
    
# Acumular resultados mensuales ---------------------------------------------

# Lista para almacenar resutlados
resultados_mensuales = []

# Reutilizar los polígonos transformados mientras el CRS no cambie
crs_anterior = None
municipios_raster = None


for fecha, ruta in tqdm(zip(periodos, rutas)):
    
    # Abrir temporalmente el archivo mensual
    with rasterio.open(ruta) as src:
        
        # Revisar que el ráster tenga información geográfica
        if src.crs is None or not src.crs.is_geographic:
            raise ValueError(f"{ruta.name}: se requiere un CRS geográfico.")
            
        # Revisar si el crs del raster es diferente al del anterior archivo
        if src.crs != crs_anterior:
            # transformar poligonos a las nuevas coordenadas
            municipios_raster = gdf_municipios[[col_id, "geometry"]].to_crs(src.crs)
            crs_anterior = src.crs # actualizar variable auxiliar para el proximo mes
        
        # Calcular media espacila ponderada por área
        resultados = exact_extract(
            src,
            municipios_raster,
            ["precipitacion_media=mean(coverage_weight=area_spherical_m2)"],
            include_cols=[col_id],
            output="pandas",
        )
    
    # Identificar el periodo del archivo
    resultados["anno"] = fecha.year
    resultados["mes"] = fecha.month
    resultados["fecha"] = fecha
    
    # Almacenar resultados mensuales
    resultados_mensuales.append(resultados)

320it [1:46:38, 20.00s/it]

In [9]:
# Consolidar el panel municipio-mes, sin geometría
panel_precipitacion = (
    pd.concat(resultados_mensuales, ignore_index=True)
    [[col_id, "anno", "mes", "fecha", "precipitacion_media"]]
    .sort_values([col_id, "fecha"])
    .reset_index(drop=True)
)

# Explorar panel
print(f"Municipios: {panel_precipitacion[col_id].nunique():,}")
print(f"Meses: {panel_precipitacion['fecha'].nunique()}")
print(f"Filas: {len(panel_precipitacion):,}")

# mostrar el panel
display(panel_precipitacion.head())



# Cada iteracion toma entre 20-40 segundos
# Como en total son 548 meses, el tiempo de ejecución varía entre 3 - 6 horas
# Si lo ejecuto solo para el periodo de interés i.e. 2006-2014, el tiempo sería menor pero seguiría siendo importante
# por eso, voy a exportar los resultados parciales
ruta_respaldo = DATA / "intermediate/e1011_precipitacion_temporal.pkl"
panel_precipitacion.to_pickle(ruta_respaldo)

Municipios: 1,122
Meses: 320
Filas: 359,040

  mpio_cdpmp  anno  mes      fecha  precipitacion_media
0      05001  2000    1 2000-01-01                66.21
1      05001  2000    2 2000-02-01               135.32
2      05001  2000    3 2000-03-01               154.53
3      05001  2000    4 2000-04-01               211.50
4      05001  2000    5 2000-05-01               336.70

# CHIRTS - Temperatura máxima

In [10]:
# Carpeta de los archivos
ruta_carpeta = DATA / "raw/acb_CHIRTS_temperatura"

# DF con los periodos en los que tengo informacion
periodos = pd.date_range(
    start="2000-01-01",
    end="2026-08-01",
    freq="MS",
)

# Comprobar que estén todos los archivos antes de procesarlos ----------------

# Crear los nombres de los archivos
rutas = [ruta_carpeta / f"CHIRTS-ERA5.monthly_Tmax.{fecha.year}.{fecha.month:02d}.tif" for fecha in periodos]

# Revisar faltantes
faltantes = [ruta.name for ruta in rutas if not ruta.exists()]

# Reportar faltantes
if faltantes:
    raise FileNotFoundError(
        f"Faltan {len(faltantes)} archivos:\n" + "\n".join(faltantes)
    )
    
    
# Acumular resultados mensuales ---------------------------------------------

# Lista para almacenar resutlados
resultados_mensuales = []

# Reutilizar los polígonos transformados mientras el CRS no cambie
crs_anterior = None
municipios_raster = None


for fecha, ruta in tqdm(zip(periodos, rutas), total=len(periodos), desc="Extrayendo precipitación"):
    
    # Abrir temporalmente el archivo mensual
    with rasterio.open(ruta) as src:
        
        # Revisar que el ráster tenga información geográfica
        if src.crs is None or not src.crs.is_geographic:
            raise ValueError(f"{ruta.name}: se requiere un CRS geográfico.")
            
        # Revisar si el crs del raster es diferente al del anterior archivo
        if src.crs != crs_anterior:
            # transformar poligonos a las nuevas coordenadas
            municipios_raster = gdf_municipios[[col_id, "geometry"]].to_crs(src.crs)
            crs_anterior = src.crs # actualizar variable auxiliar para el proximo mes
        
        # Calcular media espacila ponderada por área
        resultados = exact_extract(
            src,
            municipios_raster,
            ["Tmax_media=mean(coverage_weight=area_spherical_m2)"],
            include_cols=[col_id],
            output="pandas",
        )
    
    # Identificar el periodo del archivo
    resultados["anno"] = fecha.year
    resultados["mes"] = fecha.month
    resultados["fecha"] = fecha
    
    # Almacenar resultados mensuales
    resultados_mensuales.append(resultados)

Extrayendo precipitación: 100%|██████████| 320/320 [1:42:55<00:00, 19.30s/it]

In [11]:
# Consolidar el panel municipio-mes, sin geometría
panel_Tmax = (
    pd.concat(resultados_mensuales, ignore_index=True)
    [[col_id, "anno", "mes", "fecha", "Tmax_media"]]
    .sort_values([col_id, "fecha"])
    .reset_index(drop=True)
)

# Explorar panel
print(f"Municipios: {panel_Tmax[col_id].nunique():,}")
print(f"Meses: {panel_Tmax['fecha'].nunique()}")
print(f"Filas: {len(panel_Tmax):,}")

# mostrar el panel
display(panel_Tmax.head())



# Cada iteracion toma entre 20-40 segundos
# Como en total son 548 meses, el tiempo de ejecución varía entre 3 - 6 horas
# Si lo ejecuto solo para el periodo de interés i.e. 2006-2014, el tiempo sería menor pero seguiría siendo importante
# por eso, voy a exportar los resultados parciales
ruta_respaldo = DATA / "intermediate/e1011_Tmax_temporal.pkl"
panel_Tmax.to_pickle(ruta_respaldo)

Municipios: 1,122
Meses: 320
Filas: 359,040

  mpio_cdpmp  anno  mes      fecha  Tmax_media
0      05001  2000    1 2000-01-01       21.44
1      05001  2000    2 2000-02-01       21.76
2      05001  2000    3 2000-03-01       21.92
3      05001  2000    4 2000-04-01       22.42
4      05001  2000    5 2000-05-01       22.62

# CHIRTS - Temperatura mínima

In [12]:
# Carpeta de los archivos
ruta_carpeta = DATA / "raw/acb_CHIRTS_temperatura"

# DF con los periodos en los que tengo informacion
periodos = pd.date_range(
    start="2000-01-01",
    end="2026-08-01",
    freq="MS",
)

# Comprobar que estén todos los archivos antes de procesarlos ----------------

# Crear los nombres de los archivos
rutas = [ruta_carpeta / f"CHIRTS-ERA5.monthly_Tmin.{fecha.year}.{fecha.month:02d}.tif" for fecha in periodos]

# Revisar faltantes
faltantes = [ruta.name for ruta in rutas if not ruta.exists()]

# Reportar faltantes
if faltantes:
    raise FileNotFoundError(
        f"Faltan {len(faltantes)} archivos:\n" + "\n".join(faltantes)
    )
    
    
# Acumular resultados mensuales ---------------------------------------------

# Lista para almacenar resutlados
resultados_mensuales = []

# Reutilizar los polígonos transformados mientras el CRS no cambie
crs_anterior = None
municipios_raster = None


for fecha, ruta in tqdm(zip(periodos, rutas), total=len(periodos), desc="Extrayendo precipitación"):
    
    # Abrir temporalmente el archivo mensual
    with rasterio.open(ruta) as src:
        
        # Revisar que el ráster tenga información geográfica
        if src.crs is None or not src.crs.is_geographic:
            raise ValueError(f"{ruta.name}: se requiere un CRS geográfico.")
            
        # Revisar si el crs del raster es diferente al del anterior archivo
        if src.crs != crs_anterior:
            # transformar poligonos a las nuevas coordenadas
            municipios_raster = gdf_municipios[[col_id, "geometry"]].to_crs(src.crs)
            crs_anterior = src.crs # actualizar variable auxiliar para el proximo mes
        
        # Calcular media espacila ponderada por área
        resultados = exact_extract(
            src,
            municipios_raster,
            ["Tmin_media=mean(coverage_weight=area_spherical_m2)"],
            include_cols=[col_id],
            output="pandas",
        )
    
    # Identificar el periodo del archivo
    resultados["anno"] = fecha.year
    resultados["mes"] = fecha.month
    resultados["fecha"] = fecha
    
    # Almacenar resultados mensuales
    resultados_mensuales.append(resultados)

Extrayendo precipitación: 100%|██████████| 320/320 [1:28:52<00:00, 16.66s/it]

In [13]:
# Consolidar el panel municipio-mes, sin geometría
panel_Tmin = (
    pd.concat(resultados_mensuales, ignore_index=True)
    [[col_id, "anno", "mes", "fecha", "Tmin_media"]]
    .sort_values([col_id, "fecha"])
    .reset_index(drop=True)
)

# Explorar panel
print(f"Municipios: {panel_Tmin[col_id].nunique():,}")
print(f"Meses: {panel_Tmin['fecha'].nunique()}")
print(f"Filas: {len(panel_Tmin):,}")

# mostrar el panel
display(panel_Tmin.head())



# Cada iteracion toma entre 20-40 segundos
# Como en total son 548 meses, el tiempo de ejecución varía entre 3 - 6 horas
# Si lo ejecuto solo para el periodo de interés i.e. 2006-2014, el tiempo sería menor pero seguiría siendo importante
# por eso, voy a exportar los resultados parciales
ruta_respaldo = DATA / "intermediate/e1011_Tmin_temporal.pkl"
panel_Tmin.to_pickle(ruta_respaldo)

Municipios: 1,122
Meses: 320
Filas: 359,040

  mpio_cdpmp  anno  mes      fecha  Tmin_media
0      05001  2000    1 2000-01-01       11.94
1      05001  2000    2 2000-02-01       12.13
2      05001  2000    3 2000-03-01       12.12
3      05001  2000    4 2000-04-01       12.07
4      05001  2000    5 2000-05-01       13.04

# Organizar datos

## Cargar datos intermedios

In [14]:
# Recuperar ruta de los archivos temporales
ruta_respaldo_precipitacion = DATA / "intermediate/e1011_precipitacion_temporal.pkl"
ruta_respaldo_Tmax = DATA / "intermediate/e1011_Tmax_temporal.pkl"
ruta_respaldo_Tmin = DATA / "intermediate/e1011_Tmin_temporal.pkl"

# Cargar los archivos intermedios que se exportaron en las secciones anteriores
df_precipitacion = pd.read_pickle(ruta_respaldo_precipitacion)
df_Tmax = pd.read_pickle(ruta_respaldo_Tmax)
df_Tmin = pd.read_pickle(ruta_respaldo_Tmin)

# mostrar estructura de los datos
print(MSC_SEPARADOR, "Precitación")
display(df_precipitacion.head(3))
print(MSC_SEPARADOR, "Temperatura Max")
display(df_Tmax.head(3))
print(MSC_SEPARADOR, "Temperatura Min")
display(df_Tmin.head(3))

-------------------------------- Precitación

  mpio_cdpmp  anno  mes      fecha  precipitacion_media
0      05001  2000    1 2000-01-01                66.21
1      05001  2000    2 2000-02-01               135.32
2      05001  2000    3 2000-03-01               154.53

-------------------------------- Temperatura Max

  mpio_cdpmp  anno  mes      fecha  Tmax_media
0      05001  2000    1 2000-01-01       21.44
1      05001  2000    2 2000-02-01       21.76
2      05001  2000    3 2000-03-01       21.92

-------------------------------- Temperatura Min

  mpio_cdpmp  anno  mes      fecha  Tmin_media
0      05001  2000    1 2000-01-01       11.94
1      05001  2000    2 2000-02-01       12.13
2      05001  2000    3 2000-03-01       12.12

In [15]:
# unir datos en un solo df
claves_merge = ["mpio_cdpmp", "anno", "mes", "fecha"]

df_clima = (
    df_precipitacion
    .merge(df_Tmax, on=claves_merge, how="outer", validate="one_to_one")
    .merge(df_Tmin, on=claves_merge, how="outer", validate="one_to_one")
    .sort_values(["mpio_cdpmp", "anno", "mes"])
    .reset_index(drop=True)
)

In [21]:
# Agregar anualmente
df_clima_anual = (
    df_clima.groupby(["mpio_cdpmp", "anno"], as_index=False)
    .agg(
        precipitacion_anual = ("precipitacion_media", lambda x: x.sum(min_count=12)),
        Tmax_media_anual = ("Tmax_media", "mean"),
        Tmin_media_anual = ("Tmin_media", "mean"),
        meses_Tmax=("Tmax_media", "count"), # Columna auxiliar para contar observaciones por año 
        meses_Tmin=("Tmin_media", "count") # Columna auxiliar para contar observaciones por año
    )
)

# Dejar como faltantes los promerios de años incompletos
for variable, conteo in [("Tmax_media_anual", "meses_Tmax"), ("Tmin_media_anual", "meses_Tmin")]:
    df_clima_anual.loc[df_clima_anual[conteo] < 12, variable] = float("nan")
    
# Eliminar columnas auxiliares
df_clima_anual = df_clima_anual.drop(columns=["meses_Tmax", "meses_Tmin"])

# Mostrar datos
print(MSC_SEPARADOR, "Panel variables climaticas")
display(df_clima_anual)

-------------------------------- Panel variables climaticas

      mpio_cdpmp  anno  precipitacion_anual  Tmax_media_anual  Tmin_media_anual
0          05001  2000             2,436.31             22.43             12.32
1          05001  2001             1,914.74             22.95             12.23
2          05001  2002             2,019.04             23.39             12.22
3          05001  2003             2,201.02             23.15             12.48
4          05001  2004             2,371.09             22.85             12.86
...          ...   ...                  ...               ...               ...
30289      99773  2022             3,037.36             32.20             24.70
30290      99773  2023             2,650.31             33.01             25.30
30291      99773  2024             2,751.10             33.33             25.74
30292      99773  2025             3,001.05             32.03             25.56
30293      99773  2026                  NaN               NaN               NaN

[30294 rows x 5 columns]

## Dar estructura convenida al DF

In [24]:
# Asignar nombres de varibales para usar en STATA
df_clima_anual_stata = df_clima_anual.copy()

# Nombres de columnas
df_clima_anual_stata = df_clima_anual_stata.rename(
    columns={
        "mpio_cdpmp":COL_ID_MUNICIPIO,
        "anno":COL_ANNO,
        "precipitacion_anual":"clima_precpt_anual_tot_mm",
        "Tmax_media_anual":"clima_tmprtr_max_med_gCel",
        "Tmin_media_anual":"clima_tmprtr_min_med_gCel",
    }
)

# Mostrar DF
print(MSC_SEPARADOR, "Datafram para STATA")
display(df_clima_anual_stata)

-------------------------------- Datafram para STATA

      codigo_dane_municipio  anno  clima_precpt_anual_tot_mm  clima_tmprtr_max_med_gCel  clima_tmprtr_min_med_gCel
0                     05001  2000                   2,436.31                      22.43                      12.32
1                     05001  2001                   1,914.74                      22.95                      12.23
2                     05001  2002                   2,019.04                      23.39                      12.22
3                     05001  2003                   2,201.02                      23.15                      12.48
4                     05001  2004                   2,371.09                      22.85                      12.86
...                     ...   ...                        ...                        ...                        ...
30289                 99773  2022                   3,037.36                      32.20                      24.70
30290                 99773  2023                   2,650.31                      33.01                      25.30
30291                 99773  2024                   2,751.10                      33.33                      25.74
30292                 99773  2025                   3,001.05                      32.03                      25.56
30293                 99773  2026                        NaN                        NaN                        NaN

[30294 rows x 5 columns]

In [25]:
# Exportar a STATA
df_clima_anual_stata.to_stata(DATA/"intermediate/e1011_panel_indicadoresEspaciales_clima.dta")